/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_andrésnuila;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author enuil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        tf_BaseEscuadron.setText("");
        tf_NombreEscuadron.setText("");
        tf_DebilidadPersonaje.setText("");
        tf_FisicaPersonaje.setText("");
        tf_MentalPersonaje.setText("");
        tf_fuerzaPesonaje.setText("");
        tf_nombrePersonaje.setText("");
        tf_poderpersonaje.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personajes = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombrePersonaje = new javax.swing.JTextField();
        tf_poderpersonaje = new javax.swing.JTextField();
        tf_DebilidadPersonaje = new javax.swing.JTextField();
        rb_HeroePersonaje = new javax.swing.JRadioButton();
        rb_VillanoPersonaje = new javax.swing.JRadioButton();
        cb_Squadsheroes = new javax.swing.JComboBox<>();
        tf_fuerzaPesonaje = new javax.swing.JTextField();
        tf_FisicaPersonaje = new javax.swing.JTextField();
        tf_MentalPersonaje = new javax.swing.JTextField();
        jb_crearPersonaje = new javax.swing.JButton();
        cb_SquadsVillanos = new javax.swing.JComboBox<>();
        escuadrones = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_NombreEscuadron = new javax.swing.JTextField();
        tf_BaseEscuadron = new javax.swing.JTextField();
        rb_VillanosEsc = new javax.swing.JRadioButton();
        rb_HeroesEsc = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        TipoSquad = new javax.swing.ButtonGroup();
        tipo_personaje = new javax.swing.ButtonGroup();
        jd_arbol = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_Arbol = new javax.swing.JTree();
        jd_ListasSquads = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Squads = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jd_listasPersonajes = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Heroes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Villanos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Eliminar_Personaje = new javax.swing.JButton();
        jb_ModificarPersonaje = new javax.swing.JButton();
        popUp_Arbol = new javax.swing.JPopupMenu();
        Crear_Lider = new javax.swing.JMenuItem();
        Ver_datos = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        EscuadronMenu = new javax.swing.JMenu();
        Crear_Squad = new javax.swing.JMenuItem();
        Arbol_Squads = new javax.swing.JMenuItem();
        Listas_Squads = new javax.swing.JMenuItem();
        PersonajesMenu = new javax.swing.JMenu();
        Crear_Personaje = new javax.swing.JMenuItem();
        Listas_Personajes = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Poder");

        jLabel3.setText("Debilidad");

        jLabel4.setText("Escuadron");

        jLabel5.setText("Heroe o villano");

        jLabel6.setText("Fuerza");

        jLabel7.setText("Agilidad Fisica");

        jLabel8.setText("Agilidad Mental");

        tf_nombrePersonaje.setText("jTextField1");

        tf_poderpersonaje.setText("jTextField2");

        tf_DebilidadPersonaje.setText("jTextField3");

        tipo_personaje.add(rb_HeroePersonaje);
        rb_HeroePersonaje.setText("Heroe");
        rb_HeroePersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_HeroePersonajeItemStateChanged(evt);
            }
        });

        tipo_personaje.add(rb_VillanoPersonaje);
        rb_VillanoPersonaje.setText("VIillano");
        rb_VillanoPersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_VillanoPersonajeItemStateChanged(evt);
            }
        });

        cb_Squadsheroes.setEnabled(false);

        tf_fuerzaPesonaje.setText("jTextField4");

        tf_FisicaPersonaje.setText("jTextField5");

        tf_MentalPersonaje.setText("jTextField6");

        jb_crearPersonaje.setText("Crear");
        jb_crearPersonaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearPersonajeMouseClicked(evt);
            }
        });

        cb_SquadsVillanos.setEnabled(false);

        javax.swing.GroupLayout personajesLayout = new javax.swing.GroupLayout(personajes.getContentPane());
        personajes.getContentPane().setLayout(personajesLayout);
        personajesLayout.setHorizontalGroup(
            personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personajesLayout.createSequentialGroup()
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personajesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personajesLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombrePersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(tf_poderpersonaje)
                                        .addComponent(tf_DebilidadPersonaje))
                                    .addGroup(personajesLayout.createSequentialGroup()
                                        .addComponent(rb_HeroePersonaje)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_VillanoPersonaje))
                                    .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_MentalPersonaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(tf_FisicaPersonaje, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_fuerzaPesonaje, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(personajesLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(cb_Squadsheroes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(cb_SquadsVillanos, 0, 145, Short.MAX_VALUE))))
                    .addGroup(personajesLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jb_crearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        personajesLayout.setVerticalGroup(
            personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personajesLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombrePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_poderpersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_DebilidadPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_HeroePersonaje)
                    .addComponent(rb_VillanoPersonaje))
                .addGap(18, 18, 18)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Squadsheroes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_SquadsVillanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_fuerzaPesonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_FisicaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_MentalPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jb_crearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLabel9.setText("Nombre del Escuadron");

        jLabel10.setText("Base del Escuadron");

        jLabel11.setText("Tipo Escuadron");

        tf_NombreEscuadron.setText("jTextField7");

        tf_BaseEscuadron.setText("jTextField8");

        TipoSquad.add(rb_VillanosEsc);
        rb_VillanosEsc.setText("Villanos");

        TipoSquad.add(rb_HeroesEsc);
        rb_HeroesEsc.setText("Heroes");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout escuadronesLayout = new javax.swing.GroupLayout(escuadrones.getContentPane());
        escuadrones.getContentPane().setLayout(escuadronesLayout);
        escuadronesLayout.setHorizontalGroup(
            escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escuadronesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(escuadronesLayout.createSequentialGroup()
                        .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escuadronesLayout.createSequentialGroup()
                                .addComponent(rb_VillanosEsc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_HeroesEsc))
                            .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_NombreEscuadron, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(tf_BaseEscuadron))))
                    .addGroup(escuadronesLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        escuadronesLayout.setVerticalGroup(
            escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escuadronesLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tf_NombreEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_BaseEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rb_VillanosEsc)
                    .addComponent(rb_HeroesEsc))
                .addGap(146, 146, 146)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Escuadrones");
        jt_Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ArbolMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jt_Arbol);

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jl_Squads.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_Squads);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Heroes");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Villanos");

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");

        javax.swing.GroupLayout jd_ListasSquadsLayout = new javax.swing.GroupLayout(jd_ListasSquads.getContentPane());
        jd_ListasSquads.getContentPane().setLayout(jd_ListasSquadsLayout);
        jd_ListasSquadsLayout.setHorizontalGroup(
            jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(78, 78, 78))
                    .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ListasSquadsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jd_ListasSquadsLayout.setVerticalGroup(
            jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jl_Heroes.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_Heroes);

        jl_Villanos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_Villanos);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("HEROES");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("VILLANOS");

        Eliminar_Personaje.setText("Eliminar");
        Eliminar_Personaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_PersonajeMouseClicked(evt);
            }
        });

        jb_ModificarPersonaje.setText("Modificar");
        jb_ModificarPersonaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModificarPersonajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listasPersonajesLayout = new javax.swing.GroupLayout(jd_listasPersonajes.getContentPane());
        jd_listasPersonajes.getContentPane().setLayout(jd_listasPersonajesLayout);
        jd_listasPersonajesLayout.setHorizontalGroup(
            jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar_Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ModificarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jd_listasPersonajesLayout.setVerticalGroup(
            jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_Personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ModificarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        Crear_Lider.setText("jMenuItem1");
        Crear_Lider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Crear_LiderMouseClicked(evt);
            }
        });
        popUp_Arbol.add(Crear_Lider);

        Ver_datos.setText("jMenuItem1");
        popUp_Arbol.add(Ver_datos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EscuadronMenu.setText("ESCUADRONES");

        Crear_Squad.setText("Crear");
        Crear_Squad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_SquadActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Crear_Squad);

        Arbol_Squads.setText("Arbol de Squads");
        Arbol_Squads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arbol_SquadsActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Arbol_Squads);

        Listas_Squads.setText("Listas");
        Listas_Squads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listas_SquadsActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Listas_Squads);

        jMenuBar1.add(EscuadronMenu);

        PersonajesMenu.setText("PERSONAJES");

        Crear_Personaje.setText("Crear");
        Crear_Personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_PersonajeActionPerformed(evt);
            }
        });
        PersonajesMenu.add(Crear_Personaje);

        Listas_Personajes.setText("Listas");
        Listas_Personajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listas_PersonajesActionPerformed(evt);
            }
        });
        PersonajesMenu.add(Listas_Personajes);

        jMenuBar1.add(PersonajesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_PersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_PersonajeActionPerformed
        personajes.setModal(true);
        personajes.pack();
        personajes.setLocationRelativeTo(this);
        personajes.setVisible(true);
    }//GEN-LAST:event_Crear_PersonajeActionPerformed

    private void Crear_SquadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_SquadActionPerformed
        escuadrones.setModal(true);
        escuadrones.pack();
        escuadrones.setLocationRelativeTo(this);
        escuadrones.setVisible(true);
    }//GEN-LAST:event_Crear_SquadActionPerformed

    private void Arbol_SquadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arbol_SquadsActionPerformed
        jd_arbol.setModal(true);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);
    }//GEN-LAST:event_Arbol_SquadsActionPerformed

    private void Listas_SquadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listas_SquadsActionPerformed
        jd_ListasSquads.setModal(true);
        jd_ListasSquads.pack();
        jd_ListasSquads.setLocationRelativeTo(this);
        jd_ListasSquads.setVisible(true);
    }//GEN-LAST:event_Listas_SquadsActionPerformed

    private void Listas_PersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listas_PersonajesActionPerformed
        jd_listasPersonajes.setModal(true);
        jd_listasPersonajes.pack();
        jd_listasPersonajes.setLocationRelativeTo(this);
        jd_listasPersonajes.setVisible(true);
    }//GEN-LAST:event_Listas_PersonajesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            String nombre = tf_NombreEscuadron.getText();
            String base = tf_BaseEscuadron.getText();
            String tipo = "";
            if (rb_HeroesEsc.isSelected()) {
                tipo = "Heroe";
            } else if (rb_VillanosEsc.isSelected()) {
                tipo = "Villano";
            }
            Escuadron e = new Escuadron(nombre, base, tipo);

            String clasifificacion = e.getTipo();
            if (clasifificacion.equals("Heroe")) {
                DefaultComboBoxModel cb = (DefaultComboBoxModel) cb_Squadsheroes.getModel();
                cb.addElement(e);
                cb_Squadsheroes.setModel(cb);
            } else if (clasifificacion.equals("Villano")) {
                DefaultComboBoxModel cb = (DefaultComboBoxModel) cb_SquadsVillanos.getModel();
                cb.addElement(e);
                cb_SquadsVillanos.setModel(cb);
            }

            DefaultListModel m = (DefaultListModel) jl_Squads.getModel();
            m.addElement(e);
            jl_Squads.setModel(m);
            tf_BaseEscuadron.setText("");
            tf_NombreEscuadron.setText("");
            JOptionPane.showMessageDialog(this, "Se ha creado con exito");

            DefaultTreeModel modelo = (DefaultTreeModel) jt_Arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

            DefaultMutableTreeNode n = new DefaultMutableTreeNode(e.getNombre());

            raiz.add(n);
            modelo.reload();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_crearPersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearPersonajeMouseClicked
        try {
            String nombre = tf_nombrePersonaje.getText();
            String poder = tf_poderpersonaje.getText();
            String debilidad = tf_DebilidadPersonaje.getText();
            String tipo = "";
            if (rb_HeroePersonaje.isSelected()) {
                tipo = "Heroe";
                cb_SquadsVillanos.setEnabled(false);
            } else if (rb_VillanoPersonaje.isSelected()) {
                tipo = "Villano";
                cb_Squadsheroes.setEnabled(false);
            }
            int fuerza = Integer.parseInt(tf_fuerzaPesonaje.getText());
            int mental = Integer.parseInt(tf_MentalPersonaje.getText());
            int fisico = Integer.parseInt(tf_FisicaPersonaje.getText());
            int aux = fuerza + mental + fisico;
            if (aux != 100) {
                JOptionPane.showMessageDialog(this, "NO AJUSTA ESTE VALOR PARA SER HEROE", "VALOR INCORRECTO", JOptionPane.ERROR_MESSAGE);

            } else {
                Escuadron squad = new Escuadron();
                if (tipo.equals("Heroe")) {
                    squad = (Escuadron) cb_Squadsheroes.getSelectedItem();
                } else if (tipo.equals("Villano")) {
                    squad = (Escuadron) cb_SquadsVillanos.getSelectedItem();
                }

                Personaje p = new Personaje(nombre, poder, debilidad, squad, fuerza, fisico, mental, tipo);
                JOptionPane.showMessageDialog(this, "Se ha creado con exito");
                ((Escuadron) squad).getMiembros().add(p);

                DefaultTreeModel modelo = (DefaultTreeModel) jt_Arbol.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

                String escuadron = squad.getNombre();

                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(escuadron)) {
                        DefaultMutableTreeNode f = new DefaultMutableTreeNode(p);
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(f);
                    }
                }
                modelo.reload();

                if (tipo.equals("Heroe")) {
                    DefaultListModel th = (DefaultListModel) jl_Heroes.getModel();
                    th.addElement(p);
                    jl_Heroes.setModel(th);
                    tf_DebilidadPersonaje.setText("");
                    tf_FisicaPersonaje.setText("");
                    tf_MentalPersonaje.setText("");
                    tf_fuerzaPesonaje.setText("");
                    tf_nombrePersonaje.setText("");
                    tf_poderpersonaje.setText("");
                } else if (tipo.equals("Villano")) {
                    DefaultListModel tv = (DefaultListModel) jl_Villanos.getModel();
                    tv.addElement(p);
                    jl_Villanos.setModel(tv);
                    tf_DebilidadPersonaje.setText("");
                    tf_FisicaPersonaje.setText("");
                    tf_MentalPersonaje.setText("");
                    tf_fuerzaPesonaje.setText("");
                    tf_nombrePersonaje.setText("");
                    tf_poderpersonaje.setText("");
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }


    }//GEN-LAST:event_jb_crearPersonajeMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        if (jl_Squads.getSelectedIndex() >= 0) {
            jl_Squads.setModel(new DefaultListModel());
            DefaultListModel Hmodelo = (DefaultListModel) jl_Squads.getModel();
            Hmodelo.removeElement(jl_Squads.getSelectedIndex());
            jl_Squads.setModel(Hmodelo);
        }

    }//GEN-LAST:event_EliminarMouseClicked

    private void Eliminar_PersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_PersonajeMouseClicked
        if (jl_Heroes.getSelectedIndex() >= 0) {
            jl_Heroes.setModel(new DefaultListModel());
            DefaultListModel hmodelo = (DefaultListModel) jl_Heroes.getModel();
            hmodelo.removeElement(jl_Heroes.getSelectedIndex());
            jl_Heroes.setModel(hmodelo);
        }
        if (jl_Villanos.getSelectedIndex() >= 0) {
            jl_Villanos.setModel(new DefaultListModel());
            DefaultListModel vmodelo = (DefaultListModel) jl_Heroes.getModel();
            vmodelo.removeElement(jl_Villanos.getSelectedIndex());
            jl_Villanos.setModel(vmodelo);
        }
    }//GEN-LAST:event_Eliminar_PersonajeMouseClicked

    private void rb_HeroePersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_HeroePersonajeItemStateChanged
        cb_Squadsheroes.setEnabled(true);
        cb_SquadsVillanos.setEnabled(false);
    }//GEN-LAST:event_rb_HeroePersonajeItemStateChanged

    private void rb_VillanoPersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_VillanoPersonajeItemStateChanged
        cb_SquadsVillanos.setEnabled(true);
        cb_Squadsheroes.setEnabled(false);
    }//GEN-LAST:event_rb_VillanoPersonajeItemStateChanged

    private void jb_ModificarPersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModificarPersonajeMouseClicked
        try {
            if (jl_Heroes.getSelectedIndex() >= 0) {
                String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre: ");
                String poder = JOptionPane.showInputDialog(this, "Ingrese el poder: ");
                String debilidad = JOptionPane.showInputDialog(this, "Ingrese la debilidad: ");
                int fuerza = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la fuerza: "));
                int Fisica = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la agilidad fisica: "));
                int Mental = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la agilidad mental: "));

                while (fuerza + Fisica + Mental != 100) {
                    fuerza = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la fuerza: "));
                    Fisica = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la agilidad fisica: "));
                    Mental = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la agilidad mental: "));
                }

                Personaje p = new Personaje(nombre, poder, debilidad, fuerza, Fisica, Mental);
                jl_Heroes.setModel(new DefaultListModel());
                DefaultListModel modelo = (DefaultListModel) jl_Heroes.getModel();

                modelo.addElement(p);
                modelo.removeElementAt(jl_Heroes.getSelectedIndex());
                jl_Heroes.setModel(modelo);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valide los datos");
        }

    }//GEN-LAST:event_jb_ModificarPersonajeMouseClicked

    private void jt_ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ArbolMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_Arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_Arbol.setSelectionRow(row);
            Object v1 = jt_Arbol.getSelectionPath().getLastPathComponent();
            Personaje personaje_seleccionada = new Personaje();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
            if (nodo.getUserObject() instanceof Personaje) {
                personaje_seleccionada = (Personaje) nodo.getUserObject();
                popUp_Arbol.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_ArbolMouseClicked

    private void Crear_LiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crear_LiderMouseClicked
        int row = jt_Arbol.getClosestRowForLocation(evt.getX(), evt.getY());
        jt_Arbol.setSelectionRow(row);
        Object v1 = jt_Arbol.getSelectionPath().getLastPathComponent();
        Personaje personaje = new Personaje();
        Escuadron squad = new Escuadron();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
        if (nodo.getUserObject() instanceof Personaje) {
            personaje = (Personaje) nodo.getUserObject();
            squad = (Escuadron) nodo.getParent();
            squad.setLider(personaje);
        }
    }//GEN-LAST:event_Crear_LiderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Arbol_Squads;
    private javax.swing.JMenuItem Crear_Lider;
    private javax.swing.JMenuItem Crear_Personaje;
    private javax.swing.JMenuItem Crear_Squad;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Eliminar_Personaje;
    private javax.swing.JMenu EscuadronMenu;
    private javax.swing.JMenuItem Listas_Personajes;
    private javax.swing.JMenuItem Listas_Squads;
    private javax.swing.JButton Modificar;
    private javax.swing.JMenu PersonajesMenu;
    private javax.swing.ButtonGroup TipoSquad;
    private javax.swing.JMenuItem Ver_datos;
    private javax.swing.JComboBox<String> cb_SquadsVillanos;
    private javax.swing.JComboBox<String> cb_Squadsheroes;
    private javax.swing.JDialog escuadrones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_ModificarPersonaje;
    private javax.swing.JButton jb_crearPersonaje;
    private javax.swing.JDialog jd_ListasSquads;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JDialog jd_listasPersonajes;
    private javax.swing.JList<String> jl_Heroes;
    private javax.swing.JList<String> jl_Squads;
    private javax.swing.JList<String> jl_Villanos;
    private javax.swing.JTree jt_Arbol;
    private javax.swing.JDialog personajes;
    private javax.swing.JPopupMenu popUp_Arbol;
    private javax.swing.JRadioButton rb_HeroePersonaje;
    private javax.swing.JRadioButton rb_HeroesEsc;
    private javax.swing.JRadioButton rb_VillanoPersonaje;
    private javax.swing.JRadioButton rb_VillanosEsc;
    private javax.swing.JTextField tf_BaseEscuadron;
    private javax.swing.JTextField tf_DebilidadPersonaje;
    private javax.swing.JTextField tf_FisicaPersonaje;
    private javax.swing.JTextField tf_MentalPersonaje;
    private javax.swing.JTextField tf_NombreEscuadron;
    private javax.swing.JTextField tf_fuerzaPesonaje;
    private javax.swing.JTextField tf_nombrePersonaje;
    private javax.swing.JTextField tf_poderpersonaje;
    private javax.swing.ButtonGroup tipo_personaje;
    // End of variables declaration//GEN-END:variables

}
