/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_andrésnuila;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enuil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        tf_BaseEscuadron.setText("");
        tf_NombreEscuadron.setText("");
        tf_DebilidadPersonaje.setText("");
        tf_FisicaPersonaje.setText("");
        tf_MentalPersonaje.setText("");
        tf_fuerzaPesonaje.setText("");
        tf_nombrePersonaje.setText("");
        tf_poderpersonaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personajes = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombrePersonaje = new javax.swing.JTextField();
        tf_poderpersonaje = new javax.swing.JTextField();
        tf_DebilidadPersonaje = new javax.swing.JTextField();
        rb_HeroePersonaje = new javax.swing.JRadioButton();
        rb_VillanoPersonaje = new javax.swing.JRadioButton();
        cb_Squads = new javax.swing.JComboBox<>();
        tf_fuerzaPesonaje = new javax.swing.JTextField();
        tf_FisicaPersonaje = new javax.swing.JTextField();
        tf_MentalPersonaje = new javax.swing.JTextField();
        jb_crearPersonaje = new javax.swing.JButton();
        escuadrones = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_NombreEscuadron = new javax.swing.JTextField();
        tf_BaseEscuadron = new javax.swing.JTextField();
        rb_VillanosEsc = new javax.swing.JRadioButton();
        rb_HeroesEsc = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        TipoSquad = new javax.swing.ButtonGroup();
        tipo_personaje = new javax.swing.ButtonGroup();
        jd_arbol = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jd_ListasSquads = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_SquadsHeroes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_SquadsVillanos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jd_listasPersonajes = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Heroes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Villanos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        EscuadronMenu = new javax.swing.JMenu();
        Crear_Squad = new javax.swing.JMenuItem();
        Arbol_Squads = new javax.swing.JMenuItem();
        Listas_Squads = new javax.swing.JMenuItem();
        PersonajesMenu = new javax.swing.JMenu();
        Crear_Personaje = new javax.swing.JMenuItem();
        Listas_Personajes = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Poder");

        jLabel3.setText("Debilidad");

        jLabel4.setText("Escuadron");

        jLabel5.setText("Heroe o villano");

        jLabel6.setText("Fuerza");

        jLabel7.setText("Agilidad Fisica");

        jLabel8.setText("Agilidad Mental");

        tf_nombrePersonaje.setText("jTextField1");

        tf_poderpersonaje.setText("jTextField2");

        tf_DebilidadPersonaje.setText("jTextField3");

        tipo_personaje.add(rb_HeroePersonaje);
        rb_HeroePersonaje.setText("Heroe");

        tipo_personaje.add(rb_VillanoPersonaje);
        rb_VillanoPersonaje.setText("VIillano");

        tf_fuerzaPesonaje.setText("jTextField4");

        tf_FisicaPersonaje.setText("jTextField5");

        tf_MentalPersonaje.setText("jTextField6");

        jb_crearPersonaje.setText("Crear");
        jb_crearPersonaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearPersonajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout personajesLayout = new javax.swing.GroupLayout(personajes.getContentPane());
        personajes.getContentPane().setLayout(personajesLayout);
        personajesLayout.setHorizontalGroup(
            personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personajesLayout.createSequentialGroup()
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personajesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGap(66, 66, 66)
                        .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombrePersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(tf_poderpersonaje)
                                .addComponent(tf_DebilidadPersonaje))
                            .addGroup(personajesLayout.createSequentialGroup()
                                .addComponent(rb_HeroePersonaje)
                                .addGap(18, 18, 18)
                                .addComponent(rb_VillanoPersonaje))
                            .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_MentalPersonaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(tf_FisicaPersonaje, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_fuerzaPesonaje, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_Squads, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(personajesLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jb_crearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        personajesLayout.setVerticalGroup(
            personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personajesLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombrePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_poderpersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_DebilidadPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_HeroePersonaje)
                    .addComponent(rb_VillanoPersonaje))
                .addGap(18, 18, 18)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Squads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_fuerzaPesonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_FisicaPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(personajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_MentalPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jb_crearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLabel9.setText("Nombre del Escuadron");

        jLabel10.setText("Base del Escuadron");

        jLabel11.setText("Tipo Escuadron");

        tf_NombreEscuadron.setText("jTextField7");

        tf_BaseEscuadron.setText("jTextField8");

        TipoSquad.add(rb_VillanosEsc);
        rb_VillanosEsc.setText("Villanos");

        TipoSquad.add(rb_HeroesEsc);
        rb_HeroesEsc.setText("Heroes");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout escuadronesLayout = new javax.swing.GroupLayout(escuadrones.getContentPane());
        escuadrones.getContentPane().setLayout(escuadronesLayout);
        escuadronesLayout.setHorizontalGroup(
            escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escuadronesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(escuadronesLayout.createSequentialGroup()
                        .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escuadronesLayout.createSequentialGroup()
                                .addComponent(rb_VillanosEsc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_HeroesEsc))
                            .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_NombreEscuadron, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(tf_BaseEscuadron))))
                    .addGroup(escuadronesLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        escuadronesLayout.setVerticalGroup(
            escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escuadronesLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tf_NombreEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_BaseEscuadron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escuadronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rb_VillanosEsc)
                    .addComponent(rb_HeroesEsc))
                .addGap(146, 146, 146)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Escuadrones");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jTree1);

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jl_SquadsHeroes.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_SquadsHeroes);

        jl_SquadsVillanos.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_SquadsVillanos);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Heroes");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Villanos");

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");

        javax.swing.GroupLayout jd_ListasSquadsLayout = new javax.swing.GroupLayout(jd_ListasSquads.getContentPane());
        jd_ListasSquads.getContentPane().setLayout(jd_ListasSquadsLayout);
        jd_ListasSquadsLayout.setHorizontalGroup(
            jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(78, 78, 78))
            .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_ListasSquadsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jd_ListasSquadsLayout.setVerticalGroup(
            jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListasSquadsLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(28, 28, 28)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jd_ListasSquadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jl_Heroes.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_Heroes);

        jl_Villanos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_Villanos);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("HEROES");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("VILLANOS");

        javax.swing.GroupLayout jd_listasPersonajesLayout = new javax.swing.GroupLayout(jd_listasPersonajes.getContentPane());
        jd_listasPersonajes.getContentPane().setLayout(jd_listasPersonajesLayout);
        jd_listasPersonajesLayout.setHorizontalGroup(
            jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(67, 67, 67))
        );
        jd_listasPersonajesLayout.setVerticalGroup(
            jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listasPersonajesLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_listasPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EscuadronMenu.setText("ESCUADRONES");

        Crear_Squad.setText("Crear");
        Crear_Squad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_SquadActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Crear_Squad);

        Arbol_Squads.setText("Arbol de Squads");
        Arbol_Squads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arbol_SquadsActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Arbol_Squads);

        Listas_Squads.setText("Listas");
        Listas_Squads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listas_SquadsActionPerformed(evt);
            }
        });
        EscuadronMenu.add(Listas_Squads);

        jMenuBar1.add(EscuadronMenu);

        PersonajesMenu.setText("PERSONAJES");

        Crear_Personaje.setText("Crear");
        Crear_Personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_PersonajeActionPerformed(evt);
            }
        });
        PersonajesMenu.add(Crear_Personaje);

        Listas_Personajes.setText("Listas");
        Listas_Personajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listas_PersonajesActionPerformed(evt);
            }
        });
        PersonajesMenu.add(Listas_Personajes);

        jMenuBar1.add(PersonajesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_PersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_PersonajeActionPerformed
        personajes.setModal(true);
        personajes.pack();
        personajes.setLocationRelativeTo(this);
        personajes.setVisible(true);
    }//GEN-LAST:event_Crear_PersonajeActionPerformed

    private void Crear_SquadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_SquadActionPerformed
        escuadrones.setModal(true);
        escuadrones.pack();
        escuadrones.setLocationRelativeTo(this);
        escuadrones.setVisible(true);
    }//GEN-LAST:event_Crear_SquadActionPerformed

    private void Arbol_SquadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arbol_SquadsActionPerformed
        jd_arbol.setModal(true);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);
    }//GEN-LAST:event_Arbol_SquadsActionPerformed

    private void Listas_SquadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listas_SquadsActionPerformed
        jd_ListasSquads.setModal(true);
        jd_ListasSquads.pack();
        jd_ListasSquads.setLocationRelativeTo(this);
        jd_ListasSquads.setVisible(true);
    }//GEN-LAST:event_Listas_SquadsActionPerformed

    private void Listas_PersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listas_PersonajesActionPerformed
        jd_listasPersonajes.setModal(true);
        jd_listasPersonajes.pack();
        jd_listasPersonajes.setLocationRelativeTo(this);
        jd_listasPersonajes.setVisible(true);
    }//GEN-LAST:event_Listas_PersonajesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = tf_NombreEscuadron.getText();
        String base = tf_BaseEscuadron.getText();
        String tipo = "";
        if (rb_HeroesEsc.isSelected()) {
            tipo = "Heroe";
        } else if (rb_VillanosEsc.isSelected()) {
            tipo = "Villano";
        }
        Escuadron e = new Escuadron(nombre, base, tipo);
        DefaultComboBoxModel cb = (DefaultComboBoxModel) cb_Squads.getModel();
        cb.addElement(e);
        cb_Squads.setModel(cb);
        String clasifificacion = e.getTipo();
        if (clasifificacion.equals("Heroe")) {
            DefaultListModel mHeroes = (DefaultListModel) jl_SquadsHeroes.getModel();
            mHeroes.addElement(e);
            jl_SquadsHeroes.setModel(mHeroes);
            tf_BaseEscuadron.setText("");
            tf_NombreEscuadron.setText("");
        } else if (clasifificacion.equals("Villano")) {
            DefaultListModel mVillanos = (DefaultListModel) jl_SquadsVillanos.getModel();
            mVillanos.addElement(e);
            jl_SquadsVillanos.setModel(mVillanos);
            tf_BaseEscuadron.setText("");
            tf_NombreEscuadron.setText("");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_crearPersonajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearPersonajeMouseClicked
        String nombre = tf_nombrePersonaje.getText();
        String poder = tf_poderpersonaje.getText();
        String debilidad = tf_DebilidadPersonaje.getText();
        String tipo = "";
        if (rb_HeroePersonaje.isSelected()) {
            tipo = "Heroe";
        } else if (rb_VillanoPersonaje.isSelected()) {
            tipo = "Villano";
        }
        int fuerza = Integer.parseInt(tf_fuerzaPesonaje.getText());
        int mental = Integer.parseInt(tf_MentalPersonaje.getText());
        int fisico = Integer.parseInt(tf_FisicaPersonaje.getText());
        int aux = fuerza + mental + fisico;
        if (aux != 100) {
            JOptionPane.showMessageDialog(this, "NO AJUSTA ESTE VALOR PARA SER HEROE", "VALOR INCORRECTO", JOptionPane.ERROR_MESSAGE);

        } else {
            Escuadron squad = (Escuadron) cb_Squads.getSelectedItem();

            Personaje p = new Personaje(nombre, poder, debilidad, squad, fuerza, fisico, mental);
            ((Escuadron) squad).getMiembros().add(p);

            if (tipo.equals("Heroe")) {
                DefaultListModel th = (DefaultListModel) jl_Heroes.getModel();
                th.addElement(p);
                jl_Heroes.setModel(th);
                tf_DebilidadPersonaje.setText("");
                tf_FisicaPersonaje.setText("");
                tf_MentalPersonaje.setText("");
                tf_fuerzaPesonaje.setText("");
                tf_nombrePersonaje.setText("");
                tf_poderpersonaje.setText("");
            } else if (tipo.equals("Villano")) {
                DefaultListModel tv = (DefaultListModel) jl_Villanos.getModel();
                tv.addElement(p);
                jl_Villanos.setModel(tv);
                tf_DebilidadPersonaje.setText("");
                tf_FisicaPersonaje.setText("");
                tf_MentalPersonaje.setText("");
                tf_fuerzaPesonaje.setText("");
                tf_nombrePersonaje.setText("");
                tf_poderpersonaje.setText("");
            }
        }
    }//GEN-LAST:event_jb_crearPersonajeMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        if (jl_SquadsHeroes.getSelectedIndex()>=0) {
            jl_SquadsHeroes.setModel(new DefaultListModel());
            DefaultListModel Hmodelo = (DefaultListModel) jl_SquadsHeroes.getModel();
            Hmodelo.removeElement(jl_SquadsHeroes.getSelectedIndex());
            jl_SquadsHeroes.setModel(Hmodelo);
        }
        if (jl_SquadsVillanos.getSelectedIndex()>=0) {
            DefaultListModel vmodelo = (DefaultListModel) jl_SquadsVillanos.getModel();
            vmodelo.removeElement(jl_SquadsVillanos.getSelectedIndex());
            jl_SquadsVillanos.setModel(vmodelo);
        }
    }//GEN-LAST:event_EliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Arbol_Squads;
    private javax.swing.JMenuItem Crear_Personaje;
    private javax.swing.JMenuItem Crear_Squad;
    private javax.swing.JButton Eliminar;
    private javax.swing.JMenu EscuadronMenu;
    private javax.swing.JMenuItem Listas_Personajes;
    private javax.swing.JMenuItem Listas_Squads;
    private javax.swing.JButton Modificar;
    private javax.swing.JMenu PersonajesMenu;
    private javax.swing.ButtonGroup TipoSquad;
    private javax.swing.JComboBox<String> cb_Squads;
    private javax.swing.JDialog escuadrones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jb_crearPersonaje;
    private javax.swing.JDialog jd_ListasSquads;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JDialog jd_listasPersonajes;
    private javax.swing.JList<String> jl_Heroes;
    private javax.swing.JList<String> jl_SquadsHeroes;
    private javax.swing.JList<String> jl_SquadsVillanos;
    private javax.swing.JList<String> jl_Villanos;
    private javax.swing.JDialog personajes;
    private javax.swing.JRadioButton rb_HeroePersonaje;
    private javax.swing.JRadioButton rb_HeroesEsc;
    private javax.swing.JRadioButton rb_VillanoPersonaje;
    private javax.swing.JRadioButton rb_VillanosEsc;
    private javax.swing.JTextField tf_BaseEscuadron;
    private javax.swing.JTextField tf_DebilidadPersonaje;
    private javax.swing.JTextField tf_FisicaPersonaje;
    private javax.swing.JTextField tf_MentalPersonaje;
    private javax.swing.JTextField tf_NombreEscuadron;
    private javax.swing.JTextField tf_fuerzaPesonaje;
    private javax.swing.JTextField tf_nombrePersonaje;
    private javax.swing.JTextField tf_poderpersonaje;
    private javax.swing.ButtonGroup tipo_personaje;
    // End of variables declaration//GEN-END:variables
}
